# 50 NumPy Function

In [100]:
import numpy as np

# Function 1

In [101]:
a = np.ones(10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


# Function 2

In [102]:
a.shape = (2,-1)
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# Function 3

In [103]:
a.dtype

dtype('float64')

# Function 4

In [104]:
b = np.linspace(1,10,5)
print(b)

[ 1.    3.25  5.5   7.75 10.  ]


# Function 5

In [105]:
c = np.arange(3,20,5)
print(c)

[ 3  8 13 18]


# Function 6

In [106]:
d = np.array((2,4,7,5))
print(d)

[2 4 7 5]


# Function 7

In [107]:
e = np.empty(8)
print(e)

[1.10416227 0.54257216 0.02931546 1.50188788 0.88961172 1.18011432
 0.41111304 0.11051881]


# Function 8

In [108]:
list = [1,2,3,4,5],[1,2,3,4,5]
g = np.array((list))
print(g)

[[1 2 3 4 5]
 [1 2 3 4 5]]


# Function 9

In [109]:
print(g.shape)

(2, 5)


# Function 10

In [110]:
h = np.random.randint(50,size=7)
print(h)

[20 39 32 25 29 33  6]


# Function 11

In [111]:
h[1]

39

# Function 12

In [112]:
h[0:4]

array([20, 39, 32, 25])

# Function 14

In [113]:
h[-1]

6

# Function 15

In [114]:
h>27

array([False,  True,  True, False,  True,  True, False])

# Function 16

In [115]:
h*2/4

array([10. , 19.5, 16. , 12.5, 14.5, 16.5,  3. ])

# Function 17

In [116]:
h*2/4

array([10. , 19.5, 16. , 12.5, 14.5, 16.5,  3. ])

# Function 18

In [117]:
h+50-70

array([  0,  19,  12,   5,   9,  13, -14])

# Function 19

In [118]:
np.ones_like(a)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# Function 20

In [119]:
np.zeros_like(a)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# Function 21

In [120]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Function 22

In [121]:
array = np.arange(10)
array[7]

7

# Function 23

In [122]:
array[2:7]

array([2, 3, 4, 5, 6])

# Function 24

In [123]:
array[2:5] = 7
print(array)

[0 1 7 7 7 5 6 7 8 9]


# Function 25

In [124]:
array_copy = array.copy()
print(array_copy)

[0 1 7 7 7 5 6 7 8 9]


# Function 26

In [125]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i

arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

# Function 27

In [126]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

# Function 28

In [127]:
arr[[-3, -5, 7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [7., 7., 7., 7.]])

# Function 29

In [128]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

# Function 30

In [129]:
np.sqrt(a)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# Function 31

In [130]:
np.exp(a)

array([[2.71828183, 2.71828183, 2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183, 2.71828183, 2.71828183]])

# Function 32

In [131]:
x = np.random.randn(7)
y = np.random.randn(7)

np.maximum(x, y)

array([ 0.07406406, -0.61836072, -0.22375736, -1.1310944 ,  1.45524028,
        0.17952451,  1.22870764])

# Function 33

In [132]:
x = np.random.randn(8)
y = np.random.randn(8)

np.maximum(x, y)

array([ 0.67147296,  0.68233148,  0.14005318,  1.30043152,  0.94907616,
        1.17664876,  0.22863934, -0.18622068])

# Function 34

In [133]:
np.abs(x)

array([0.24891252, 0.68233148, 0.21892604, 1.30043152, 2.28135823,
       0.23563335, 0.22863934, 0.61817284])

# Function 35

In [134]:
np.sign(x)

array([ 1.,  1., -1.,  1., -1., -1.,  1., -1.])

# Function 36

In [135]:
np.ceil(x)

array([ 1.,  1., -0.,  2., -2., -0.,  1., -0.])

# Function 37

In [136]:
np.floor(x)

array([ 0.,  0., -1.,  1., -3., -1.,  0., -1.])

# Function 38

In [137]:
np.rint(x)

array([ 0.,  1., -0.,  1., -2., -0.,  0., -1.])

# Function 39

In [138]:
np.isnan(x)

array([False, False, False, False, False, False, False, False])

# Function 40

In [139]:
np.add(x, y)

array([ 0.92038548, -0.04597825, -0.07887286,  2.47506684, -1.33228207,
        0.94101541, -0.09493811, -0.80439351])

# Function 41

In [140]:
np.subtract(x, y)

array([-0.42256044,  1.41064121, -0.35897921,  0.12579619, -3.23043439,
       -1.41228211,  0.55221678, -0.43195216])

# Function 42

In [141]:
np.multiply(x, y)

array([ 0.16713803, -0.49694866, -0.03066129,  1.5275328 , -2.16518271,
       -0.27725769, -0.07398253,  0.11511656])

# Function 43

In [142]:
np.divide(x, y)

array([ 0.37069627, -0.93686992, -1.56316368,  1.10709383, -2.40376729,
       -0.20025802, -0.7065985 ,  3.31957144])

# Function 44

In [143]:
np.floor_divide(x, y)

array([ 0., -1., -2.,  1., -3., -1., -1.,  3.])

# Function 45

In [144]:
np.power(4, 2)

16

# Function 46

In [145]:
np.fmax(x, y)

array([ 0.67147296,  0.68233148,  0.14005318,  1.30043152,  0.94907616,
        1.17664876,  0.22863934, -0.18622068])

# Function 47

In [146]:
np.fmin(x, y)

array([ 0.24891252, -0.72830973, -0.21892604,  1.17463532, -2.28135823,
       -0.23563335, -0.32357744, -0.61817284])

# Function 48

In [147]:
np.copysign(x, -2)

array([-0.24891252, -0.68233148, -0.21892604, -1.30043152, -2.28135823,
       -0.23563335, -0.22863934, -0.61817284])

# Function 49

In [148]:
a.mean()

1.0

# Function 50

In [149]:
a.all()

True